# Site settings
title: Tajdid Rahman
email: tajdidrahman@gmail.com
# description: "Hi there! My name's Tajdid Rahman, but you can call me Taj. This blog was created for my Project Management module that I'm currently doing for my Foundation Degree Interactive Media at the Belfast Met, Titanic Quarter."

baseurl: "/projectblog"
url: "http://tajdid.me.uk/projectblog"
permalink: /projectblog/:title.html
paginate_path: "/projectblog/page:num"

email: tajdidrahman@gmail.com
twitter_username: tajdidr
github_username:  tajdid

# Build settings
markdown: kramdown
permalink: pretty
